mkblocks: Provide an option to force prefix numbering on the first block.
spf-tools/spf-tools pull request #186
Opened 2023-01-25 06:04 UTC by richwalm

A needed feature for me, so feel it could be useful for others as well.

My reasoning for this is as follows;
The core domain I'm need SPF flattening for is registered to a provider who doesn't provide an API access for record changes.
Therefore, I'd like to reuse a secondary domain I have hosted on another provider (with API access) to host these records.
This secondary domain already has an existing SPF record which I don't want to interfere with.

Understand that there's a few ways around this, like a subdomain prefix or simply transferring the domain to the API provider, but this method is the most suitable at the moment.

2023-08-22 19:08 UTC, jcbf requested changes
Can't really think of a use case for this but works as expected.

Tests are failing. 
PR must include updated tests/mkblocks-help/out

2023-09-12 03:07 UTC, richwalm commented
I've updated the test.

2023-09-12 09:11 UTC, jcbf commented
Sorry about nitpicking but I didn't notice, but can you fix the typo?
`numbing -> numbering`

2023-09-12 12:07 UTC, richwalm commented
Whoops. No problem. Fixed now.

2023-09-12 13:59 UTC, jcbf approved these changes

2024-12-31 07:28 UTC, merged